### ISSUE TITLE
s3 put hangs for objects >=1MB

### ISSUE THREAD

**Issue by mvayngrib** [atlassian/localstack#113]
guys, thanks for the awesome project! 

Do you know why this might be the case? putObject works for 100KB, but hangs for 1MB or more. I didn't check what the exact size cutoff is

I'm running it dockerized, let me know if there's anything else you need to know about my setup

**Comment by whummer** [comment]
Thanks for reporting @mvayngrib . I wasn't able to reproduce the issue.

```
$ dd count=9999 if=/dev/zero of=/tmp/testfile.bin
$ ls -lah /tmp/testfile.bin
-rw-r--r--  1 user  group   4.9M May 27 20:41 /tmp/testfile.bin
$ aws --endpoint-url=http://localhost:4572 s3 mb s3://testbucket
$ aws --endpoint-url=http://localhost:4572 s3 cp /tmp/testfile.bin s3://testbucket/foo/123
upload: ../../tmp/testfile.bin to s3://testbucket/foo/123
# download and verify file contents
$ aws --endpoint-url=http://localhost:4572 s3 cp s3://testbucket/foo/123 /tmp/testfile1.bin
$ md5 /tmp/testfile*.bin
MD5 (/tmp/testfile.bin) = 39174f1d8e0bd53709d7e70548b18d53
MD5 (/tmp/testfile1.bin) = 39174f1d8e0bd53709d7e70548b18d53
```

It even works with files that are close to 500MB in size:
```
$ dd count=999999 if=/dev/zero of=/tmp/testfile.bin
$ ls -lah /tmp/testfile.bin
-rw-r--r--  1 user  group   488M May 27 20:42 /tmp/testfile.bin
$ aws --endpoint-url=http://localhost:4572 s3 cp /tmp/testfile.bin s3://testbucket/foo/123
upload: ../../tmp/testfile.bin to s3://testbucket/foo/123
```

Can you try running LocalStack with debug output enabled and report back the output and error messages:
```
DEBUG=1 make docker-run
```

This is the output I'm getting on my machine (this is on Mac OS):
```
...
127.0.0.1 - - [27/May/2017 23:42:32] "PUT /testbucket HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:42:53] "PUT /testbucket/foo/123 HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:44:09] "HEAD /testbucket/foo/123 HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:44:09] "GET /testbucket/foo/123 HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:01] "POST /testbucket/foo/123?uploads HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:02] "PUT /testbucket/foo/123?partNumber=7&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "PUT /testbucket/foo/123?partNumber=3&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "PUT /testbucket/foo/123?partNumber=5&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "PUT /testbucket/foo/123?partNumber=6&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "PUT /testbucket/foo/123?partNumber=2&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "PUT /testbucket/foo/123?partNumber=1&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "PUT /testbucket/foo/123?partNumber=4&uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2017 23:46:03] "POST /testbucket/foo/123?uploadId=aOOXquvrFi1YZuTYQcnxfDC8%2Fbb7taQc3zV0Ygsoskhfm6bjLtjdNazBFQ HTTP/1.1" 200 -
```

One possible issue could be memory limits - note that the S3 objects are kept in RAM, hence the container may be running out of memory. What is the memory configuration of your container? In my setup, Docker may take up to 2GB of RAM:
```
$ docker ps | grep localstack | awk '{print $1}' | xargs docker stats
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
18c22038a812        2.21%               1.788 GiB / 1.952 GiB   91.58%              1.49 GB / 4.68 MB   47.1 MB / 347 MB    130
```

**Comment by mvayngrib** [comment]
@whummer thanks for getting back to me. See my output below:
```sh
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
dc851540dfa5        1.06%               298.4 MiB / 1.952 GiB   14.93%              1.7 kB / 788 B      54.7 MB / 0 B       48
```

**Comment by mvayngrib** [comment]
@whummer happy to help investigate over Skype if you're up for it

**Comment by mvayngrib** [comment]
@whummer oops, i somehow missed the whole first part of your answer. My bad!

Running the commands you pasted works just fine. I'm using the Serverless framework and it's timing out on uploading the code zip to localstack s3. I'll see if I can gather any more clues.

**Comment by mvayngrib** [comment]
@whummer i've created a minimal [breaking test](https://github.com/mvayngrib/localstack-test/blob/master/s3.js) using the node.js aws-sdk

the test puts objects of size up to one hundred megs, starting from 1kb and doubling

you can clone it and try yourself:

```sh
git clone https://github.com/mvayngrib/localstack-test
cd localstack-test
```

and run:

```sh
~/Code/localstack-test on master
$ node s3
created bucket
putting 1KB of nonsense
successfully put 1KB of nonsense
putting 2KB of nonsense
successfully put 2KB of nonsense
putting 4KB of nonsense
successfully put 4KB of nonsense
putting 8KB of nonsense
successfully put 8KB of nonsense
putting 16KB of nonsense
successfully put 16KB of nonsense
putting 32KB of nonsense
successfully put 32KB of nonsense
putting 64KB of nonsense
successfully put 64KB of nonsense
putting 128KB of nonsense
successfully put 128KB of nonsense
putting 256KB of nonsense
successfully put 256KB of nonsense
putting 512KB of nonsense
successfully put 512KB of nonsense
putting 1024KB of nonsense
```

**Comment by whummer** [comment]
Thanks for sharing the test project, that made it a lot easier to debug. Turns out that the nodejs SDK uses `Connection: keep-alive` which was previously not supported in LocalStack. This is now fixed in commit c01ca83a039a506e6e6b455dba028359e27a5e0f . The Docker image has been updated, please pull the latest version and give it a try. Thanks

**Comment by mvayngrib** [comment]
@whummer awesome! Thanks for the amazing turnaround, will try in a bit

**Comment by mvayngrib** [comment]
@whummer still not working with the latest image, you sure the image was updated?

<img width="957" alt="screen shot 2017-05-29 at 10 37 02 am" src="https://cloud.githubusercontent.com/assets/83948/26553711/d9b7d5b6-445a-11e7-89c6-9a29071a2be1.png">

**Comment by whummer** [comment]
Apologies, that was an oversight, please pull the image now and give it another try. Cheers

**Comment by mvayngrib** [comment]
@whummer sorry, I don't see a new image: https://hub.docker.com/r/atlassianlabs/localstack/tags/
would you mind taking another look?

**Comment by mvayngrib** [comment]
@whummer ok, i see a new image now, will try :)

**Comment by mvayngrib** [comment]
@whummer awesome, that did it, thanks for the help!

**Comment by sam46** [comment]
Hi, I'm experiencing this same issue with the latest image. As a workaround I'm using an older one

**Comment by KleberMotta** [comment]
I still have the same problem here:

```
LocalStack version: 2.0.3.dev
LocalStack build date: 2023-05-19
LocalStack build git hash: 6800861b
```

**Comment by bentsku** [comment]
Hi @KleberMotta, this issue has not been reported in a while. Could you please open a new issue and describe your problem there? It certainly isn't the same issue as when this issue was reported. Thanks!

**Comment by KleberMotta** [comment]
> Hi @KleberMotta, this issue has not been reported in a while. Could you please open a new issue and describe your problem there? It certainly isn't the same issue as when this issue was reported. Thanks!

Thanks @bentsku I will open a new issue describing my problem
