### ISSUE TITLE
Problems using pip-installed version

### ISSUE THREAD

**Issue by ulsa** [atlassian/localstack#96]
Tried using localstack (0.4.1) with `pip install` on a Mac with Homebrew Python 2.7 with no virtualenv, but ran into problems.

1. It seems subprocess32 is not installed (although the changelog indicates it was fixed in 0.3.10). Manually installing it fixed that.

        $ localstack web
        ...
        ImportError: No module named subprocess32
        
        $ pip install subprocess32
        $ localstack web
        Initializing installation of Web application (this could take long time, please be patient)
         * Running on http://0.0.0.0:8080/
        
2. It seems localstack expects a `.venv` folder, which I haven't got. Accessing the web page gives me:

        ERROR: '. .venv/bin/activate; aws --endpoint-url="http://localhost:4578" es list-domain-names': /bin/sh: .venv/bin/activate: No such file or directory

So before I start delving too deep into virtualenv and stuff, is there something that needs to be done to the installation process docs/scripts, or do I need to do something more than just `pip install localstack` (and `pip install subprocess32`)?

**Comment by whummer** [comment]
Thanks for reporting. Both issues are legitimate bugs and/or invalid assumptions about the installation environment.

Regarding point 2., we should in fact be using `boto3` instead of using the `aws` CLI directly. As a quick fix, if you manage to find the file `localstack/dashboard/infra.py` in your installation folder, you could change line 78 from this:
```
cmd = '. .venv/bin/activate; aws'
```
to this:
```
cmd = '{ test `which aws` || . .venv/bin/activate; }; aws'
```
The command above will first check if the `aws` command is available and use `.venv` only if the command not installed globally. Can you please give this a try and report back if it works? We can then release a new version with this hot fix (mid-term we will do the proper fix using `boto3` instead of using the CLI).

**Comment by ulsa** [comment]
I tried that, and now the web UI first says it's looking for services, but after a few seconds it fails with this:

```
CalledProcessError: Command '{ test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4578" es list-domain-names' returned non-zero exit status 255
```

I currently have Localstack running, but only with S3.

**Comment by whummer** [comment]
@ulsa I forgot to mention that, if you make the change described above, you need to have the `aws` CLI installed as a command on your machine. What is the output of the following command?
```
aws --version
```
Does it print the version number or do you get a "command not found" error?

**Comment by ulsa** [comment]
```
aws-cli/1.11.75 Python/2.7.12 Darwin/15.6.0 botocore/1.5.38
```

**Comment by whummer** [comment]
Can you please give it a try and re-install the new version `0.4.2`? The issue with `subprocess32` should be fixed in that version.

Not sure about the other problem, though. Do you get an error if you run the command directly in your terminal?
```
{ test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4578" es list-domain-names
```

FWIW, I had to update `botocore` on my local machine to get the `aws` CLI working, maybe that helps:
```
pip install -U botocore
```

**Comment by ulsa** [comment]
Well, the command runs, but I don't have ES running, so I get a connection refused on that port.

And I still get this when I refresh the web page:

```
ERROR: '{ test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4578" es list-domain-names': 
('Connection aborted.', error(61, 'Connection refused'))

127.0.0.1 - - [10/May/2017 11:43:38] "POST /graph HTTP/1.1" 500 -
```

**Comment by whummer** [comment]
Ok I see, that makes sense. I wasn't aware that ES is not running. Will release a fix shortly. Thanks

**Comment by ulsa** [comment]
Regarding 0.4.2, it still doesn't install `subprocess32`. It replaces a new `botocore` with an older version, but that may be intentional.

```
$ pip uninstall localstack subprocess32
Uninstalling localstack-0.4.2:
...
Uninstalling subprocess32-3.2.7:
...

$ pip install localstack
...
Installing collected packages: localstack, botocore
  Found existing installation: botocore 1.5.38
    Uninstalling botocore-1.5.38:
      Successfully uninstalled botocore-1.5.38
Successfully installed botocore-1.4.93 localstack-0.4.2
```

The web UI starts, but on page load:

```
ImportError: No module named subprocess32
```

**Comment by ulsa** [comment]
I start `infra` with specific services, since I don't need all of them:

```
DEFAULT_REGION=eu-west-1 SERVICES=s3 localstack infra
```

**Comment by whummer** [comment]
The issue with failing `aws` CLI commands is fixed in ce2d37e227c1791f3c8d5dd7ccd26becba379f82 . I was unable to reproduce the installation issue with `subprocess32`, but will keep investigating. Thanks

**Comment by whummer** [comment]
PS: Another thing you could try is using pip install with the `--no-cache` option.

If you uninstall the following:
```
$ pip uninstall localstack
$ pip uninstall subprocess32
$ pip uninstall subprocess32-ext
$ python -c 'import subprocess32; print(subprocess32.__file__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named subprocess32
```

And then install localstack like this...
```
pip install --no-cache localstack
```
... then you should see following line in the output:
```
...
Collecting subprocess32-ext==3.2.8.2 (from localstack)
...
```
... and this command should work:
```
$ python -c 'import subprocess32; print(subprocess32.__file__)'
/usr/local/lib/python2.7/site-packages/subprocess32.py
```
Can you confirm that @ulsa , or do you see a different behavior?

**Comment by ulsa** [comment]
Yes, I can confirm this. `subprocess32-ext-3.2.8.2` is installed and the command works.

**Comment by whummer** [comment]
Thanks for testing. Closing this issue as solved.
